controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

privacy:
  path: /privacy-policy
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/privacy_policy.html.twig'

xss:
  path: /xss
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'static/xss.html.twig'
